spring.datasource.name=FoodFrenzy
spring.datasource.url=jdbc:mysql://localhost:3305/FoodFrenzy?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Singla1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
